### PR TITLE
Reorganizing so that it is easier to import

### PR DESCRIPTION
**Pull request by hiromis**
I am thinking of something like this so that there are no logic in `cmd` package. The only thing the caller needs to worry about are 4 arguments to send to the service (`(input string, repo string, configFile string, dest string)`).

Currently the example in `example/` does not work due to https://github.com/galaho/pathogen/issues/35 however, the behavior is consistent before and after the reorganization.

This is certainly not final and any comments/suggestions are appreciated.

### CODE REVIEW

**Comment by joshua-rutherford** [comment]
If I followed this pattern I should move the version command into `./pkg/commands` and that doesn't make any sense as it requires that you set a number of build flags.

That said, I'm not completely against moving the logic out of `/cmd` let me noodle a way to make us both happy.

**Comment by joshua-rutherford** [comment]
It think that if we did this we'd have to make the signature for the `Generate` method like so:

```
func Generate(source string, destination string, config string, resolver resolvers.Resolver) error {

}
```

The resolver should be injected to allow for extensibility.

**Comment by hiromis** [comment]
We can always wrap a function and create multiple entries. If somebody wants to send resolver, that's fine. If somebody else just want to send input string, that's fine too. At the moment, we don't really need the extensibility so `func Generate(input string, repo string, configFile string, dest string)` is preferrable and that can call `func GenerateViaResolver(resolver resolvers.Resolver, destination string,  configFile string)` which we can call when we need to do something different.

**Comment by hiromis** [comment]
> It think that if we did this we'd have to make the signature for the `Generate` method like so:
> 
> ```
> func Generate(source string, destination string, config string, resolver resolvers.Resolver) error {
> 
> }
> ```
> 
> The resolver should be injected to allow for extensibility.

Added GenerateWithResolver function.

**Comment by hiromis** [comment]
@joshua-rutherford, could you review my latest change from yesterday when you have some time?

**Comment by joshua-rutherford** [comment]
@hiromis, sorry it still don't want to do this as it makes assumptions on the usage and I don't really see why making those assumptions here makes sense.  As I said before, I think the method signature in the library functions should be:

```
func Generate(source string, destination string, config string, resolver resolvers.Resolver) error {

}
```

and then the user should be explicit in their desired behavior.  i don't think that the savings gained by making these assumptions (five lines of code on your end) are warranted.

**Pull request closed without merging**
